server:
  port: 8089
  servlet:
    context-path: /
  tomcat.basedir: log/temp
  tomcat.uri-encoding: UTF-8


spring:
  #配置 thymeleaf 模板
  thymeleaf:
    prefix: file:D:/JetBrains/projects/tool-upload/src/main/resources/static/
  servlet:
    multipart:
      #设置上传大小的
      max-file-size: 10MB
      max-request-size: 10MB
  resources:
    static-locations: classpath:log/uploader/,file:log/uploader/